"""
HyDE query rewriter for Cedant's hybrid retrieval pipeline.

For Q14 (see ``docs/open_questions.md``), retrieval misses on the
production-default cell were diagnosed as query/chunk language
asymmetry on the dense channel. HyDE (Gao et al., 2022 -- "Precise
Zero-Shot Dense Retrieval without Relevance Labels") addresses this
by replacing the query embedding with the embedding of a *hypothetical
answer passage* generated by an LLM. The passage shares the
linguistic register of likely target chunks (formal regulatory or
corporate-disclosure prose), pulling the dense embedding into a
neighbourhood the original interrogative query missed.

Cedant uses **partial HyDE**: the hypothetical passage is routed to
the dense channel only; the original query stays on the sparse (BM25)
channel. This preserves sparse-channel matches on named entities
(SS5/25, ORSA, ICAAP) and instrument identifiers that the HyDE
passage may or may not preserve verbatim. The split lives in
``Retriever.retrieve(..., use_hyde=True)``.

The prompt was selected from a 3-variant probe on 6 mechanism-clear
strict misses (see Phase 2a, ``docs/journal.md`` 2026-06-20 PM).
The constrained "imagine the literal paragraph" framing (5/6 recovery
vs 3/6 generic, 4/6 domain) is committed here as ``CONSTRAINED_PROMPT``.
The prompt is not configurable via env var by design -- changing it
would invalidate any saved evaluation runs.
"""
from __future__ import annotations

import os
from typing import Any

import httpx

# ---- Module constants ---------------------------------------------------

#: Production-default rewriter model. Same as ``AnswerGenerator`` per
#: D015. Sharing the model keeps the spike honest: a smaller, faster
#: rewriter could pass Q14's falsification criterion while not
#: reflecting the production cell. Override via the same env var as
#: ``answer.py`` so a single setting flips both components together.
DEFAULT_MODEL = "gemma-4-31B-it-MLX-6bit"

#: Env var that overrides ``DEFAULT_MODEL`` but loses to an explicit
#: ``model=`` constructor argument. Shared with ``AnswerGenerator``.
MODEL_ENV_VAR = "UNDERWRITING_COPILOT_MODEL"

#: oMLX local endpoint with OpenAI-compatible API. Matches
#: ``answer.py`` so a single oMLX serve covers both rewriting and
#: answering on the same model.
DEFAULT_API_BASE = "http://127.0.0.1:8000/v1"

#: oMLX's placeholder bearer token per ``~/.omlx/settings.json``.
#: Not a secret; exists to satisfy the OpenAI SDK contract, not to
#: provide security against an attacker with local network access.
DEFAULT_API_KEY = "claude"

DEFAULT_TIMEOUT_SECONDS = 120.0

#: Passage shape from Phase 2a probe was 187-861 chars across the 6
#: test questions; mean ~600. 250 tokens caps at roughly 1000 chars,
#: leaving headroom without inviting the model to ramble.
DEFAULT_MAX_TOKENS = 250

#: The Phase 2a chosen prompt. Variant name CONSTRAINED. Verbatim
#: from ``scripts/probes/q14_hyde_prompt_probe.py``. Changes to this
#: text invalidate previously recorded HyDE eval runs and should
#: be paired with a new ``eval/results/<timestamp>`` directory plus
#: a journal entry.
CONSTRAINED_PROMPT = """Imagine you have access to the regulatory supervisory statement or corporate sustainability report that contains the answer to this question. Write the exact paragraph from that document that contains the answer. Be specific, use technical terminology, and name any organisations or instruments referenced. One paragraph only; do not preface with commentary.

Question: {query}

Paragraph:"""


def _resolve_model(explicit: str | None) -> str:
    """Same twelve-factor precedence as ``AnswerGenerator``: explicit
    constructor argument > ``UNDERWRITING_COPILOT_MODEL`` env var >
    ``DEFAULT_MODEL``. Resolved at constructor call time, not at
    module import, so a sweep harness can flip the env var
    mid-process and have the next rewriter pick it up.
    """
    if explicit:
        return explicit
    env_val = os.environ.get(MODEL_ENV_VAR)
    if env_val:
        return env_val
    return DEFAULT_MODEL


# ---- QueryRewriter ------------------------------------------------------


class QueryRewriter:
    """Generates a hypothetical-answer passage for a user query.

    Single-shot, deterministic at ``temperature=0``. Intended to feed
    the dense channel of ``Retriever.retrieve()`` when
    ``use_hyde=True``.

    Construction is cheap (no model weights, no client state to
    preload); each ``rewrite()`` call opens its own ``httpx.Client``
    inside a ``with`` block. The HTTP-client lifecycle matches
    ``AnswerGenerator``'s ``_call_llm`` pattern for codebase
    consistency rather than reusing an outer client.
    """

    def __init__(
        self,
        model: str | None = None,
        api_base: str = DEFAULT_API_BASE,
        api_key: str = DEFAULT_API_KEY,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        prompt_template: str = CONSTRAINED_PROMPT,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        self.model = _resolve_model(model)
        self.api_base = api_base
        self.api_key = api_key
        self.timeout = timeout
        self.max_tokens = max_tokens
        self.prompt_template = prompt_template
        # ``transport`` is primarily a testing hook (httpx.MockTransport),
        # but is also a defensible production override for proxies or
        # custom TLS verification. ``None`` means use httpx's default.
        self._transport = transport

    def rewrite(self, query: str) -> str:
        """Return a hypothetical-answer passage for the query.

        Raises:
            httpx.HTTPError on transport/network failures.
            httpx.HTTPStatusError on non-2xx responses (via
                ``raise_for_status``).
            ValueError on empty or malformed LLM responses.
        """
        if not query or not query.strip():
            raise ValueError("query must be non-empty")

        prompt = self.prompt_template.format(query=query)
        with httpx.Client(
            timeout=self.timeout,
            transport=self._transport,
        ) as client:
            response = client.post(
                f"{self.api_base}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}"},
                json={
                    "model": self.model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.0,
                    "max_tokens": self.max_tokens,
                },
            )
        response.raise_for_status()
        data: dict[str, Any] = response.json()
        try:
            text = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as e:
            raise ValueError(
                f"Malformed LLM response: missing "
                f"choices[0].message.content. Got keys: "
                f"{sorted(data.keys()) if isinstance(data, dict) else type(data)!r}"
            ) from e
        if not isinstance(text, str) or not text.strip():
            raise ValueError("LLM returned empty rewrite")
        return text.strip()
